CREATE TABLE ACCOUNT_DETAILS (
    USER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FNAME VARCHAR(255) NOT NULL,
    LNAME VARCHAR(255) NOT NULL,
    DOB DATE NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);